name: world_explorer
description: Made in Ethiopia
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#013220"
  adaptive_icon_foreground: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png